trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '16.x' # replace this value with the version that you need for your project
  displayName: 'Install Node.js'
- task: DownloadSecureFile@1
  name: jwtKey
  inputs:
    secureFile: "server.key"
  displayName: 'Get JWT Key'
- script:
    npm install --global sfdx-cli
  displayName: "Install Salesforce CLI"
- script:
    sfdx force:auth:jwt:grant --clientid $(CONSUMER_KEY) --username $(USERNAME) --jwtkeyfile $(jwtKey.secureFilePath) --setalias myDevOrg
  displayName: "Authorise Salesforce Dev Org"
- script:
    sfdx force:config:set defaultusername=myDevOrg
  displayName: "Set default Org"
- script:
    sfdx force:source:deploy -m ApexClass
  displayName: "Deploying Apex Class"
