trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '10.x' # replace this value with the version that you need for your project

- script:
    npm install --global sfdx-cli
  displayName: "Install Salesforce CLI"
  